name: 🚀 Build, Test & Release Android App

on:
  push:
    tags:
      - 'v*'  # Solo se ejecuta con tags como v1.0.0

jobs:
  unit-test:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: GPS

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v5

      - name: ☕ Set up Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: 🧪 Run unit tests
        run: ./gradlew test

  instrumented-tests:
    name: 🤖 Instrumented Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: GPS

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v5

      - name: ☕ Set up Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: 🔓 Enable KVM (hardware acceleration)
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: 🤖 Run Instrumented Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_3a
          heap-size: 512M
          ram-size: 4096M
          emulator-options: -memory 4096 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          disk-size: 8G
          working-directory: GPS
          script: |
            mkdir -p artifacts/report
            adb logcat -c
            adb logcat -G 16M && adb logcat -g
            ./gradlew connectedCheck || touch tests_failing
            adb logcat -d > artifacts/logcat.txt
            cp -r app/build/reports/androidTests/connected/* artifacts/report/ || true
            if adb shell '[ -e /sdcard/Pictures/screenshots ]'; then adb pull /sdcard/Pictures/screenshots artifacts/; fi
            test ! -f tests_failing

      - name: 📤 Upload Instrumented Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: instrumented-test-report
          path: GPS/artifacts/*
          if-no-files-found: ignore

  build-release:
    name: 📦 Build & GitHub Release
    runs-on: ubuntu-latest
    needs: [unit-test]
    defaults:
      run:
        working-directory: GPS

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v5

      - name: ☕ Set up Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: 🏗️ Build Release APK
        run: ./gradlew assembleRelease

      - name: 📤 Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: GPS/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
